version: "3.7"
networks:
  project_number_one_network:
    name: project_number_one_network
services:
  nginx:
    container_name: project_number_one_nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/server.pem:/etc/nginx/server.pem
      - ./nginx/ssl/server.key:/etc/nginx/server.key
      - ./nginx/ssl/cacert.pem:/etc/nginx/cacert.pem
      - ./../:/var/www/html
    networks:
      - project_number_one_network
  php-fpm:
    container_name: project_number_one_php_fpm
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
    image: project_number_one/php-fpm
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./../:/var/www/html
    networks:
      - project_number_one_network
  mysql:
    container_name: project_number_one_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=database
    networks:
      - project_number_one_network
  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    container_name: project_number_one_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - project_number_one_network
